clearvars
clc
%This code is an example of using virtual field method to find the material
%properties, given its mechanical responses under pressure generated by 
%FE simulation
%Input data should be changed in the 'costFunc' function

% [ output_args ] = costFunc(C1,K)
% options = optimoptions('fminunc','Algorithm','quasi-newton');
% output=fminunc(@costFunc,[205,110],options);
% x = ga(@costFunc,2); %the results os x = 201.9157   89.3132 (too slow)

options=optimset('Display','final');

x=[100,100];
[x2,fval]=fminsearch(@costFunc,x,options);
disp('Initial point 1')
disp(['Optimization resuts: C1= ',num2str(x2(1)),'  K= ',num2str(x2(2))])

x=[500,250];
[x2,fval]=fminsearch(@costFunc,x,options);
disp('Initial point 2')
disp(['Optimization resuts: C1= ',num2str(x2(1)),'  K= ',num2str(x2(2))])

x=[250,500];
[x2,fval]=fminsearch(@costFunc,x,options);
disp('Initial point 3')
disp(['Optimization resuts: C1= ',num2str(x2(1)),'  K= ',num2str(x2(2))])